name: Bump casks on schedule or request

on:
  workflow_dispatch:
    inputs:
      casks:
        description: Custom list of casks to livecheck and bump if outdated
        required: false
  schedule:
    # - cron: "23 */3 * * *"
    - cron: "0 6 * * *" # daily

permissions:
  contents: write
  # pull-requests: write

jobs:
  autobump:
    if: github.repository == 'synkathairo/homebrew-repo'
    env:
      HOMEBREW_DEVELOPER: 1
    runs-on: macos-26
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          core: true
          cask: true

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@main
        with:
          username: github-actions[bot]

      - name: Bump casks
        id: autobump
        env:
          # HOMEBREW_TEST_BOT_AUTOBUMP: 1
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GIT_COMMITTER_NAME: github-actions[bot]
          HOMEBREW_GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          CASKS: ${{ inputs.casks }}
        run: |
          # BREW_BUMP=(brew bump --no-fork --open-pr --casks)
          BREW_BUMP=(brew bump-cask-pr --write-only --commit --no-audit --no-style)
          if [[ -n "${CASKS-}" ]]; then
            xargs -n1 "${BREW_BUMP[@]}" <<<"${CASKS}"
          else
            brew livecheck --json --newer-only --casks --tap=synkathairo/repo |
              ruby -rjson -e 'JSON.parse(STDIN.read).each { |cask| puts [cask["cask"], cask.dig("version", "latest")].join("\t") if cask.dig("version", "latest") }' |
              while IFS=$'\t' read -r cask version; do
                "${BREW_BUMP[@]}" --version="${version}" "${cask}"
              done
          fi

          git push
